[pytest]
addopts = --benchmark-group-by=group --benchmark-save=benchmark_file
markers =
    group1: Unit Tests
    group2: Tests belonging to the first group
    group3: Tests belonging to the second group