name: Graph Algorithm Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml  # 指定你的 conda 环境文件
          activate-environment: testenv  # 指定你的 conda 环境名称

      - name: Initialize Conda and Install dependencies
        run: bash -c "
          conda init bash
          source ~/.bashrc
          conda env update --file environment.yml --name testenv
          conda activate testenv
          pip install pytest"
        
      - name: Run tests
        run: bash -c "
          source ~/.bashrc
          conda activate testenv
          pytest"